# DEFAULT /PREDETERMINADO si no se especifica entorno
spring:
  application:
    name: UserManager
  banner:
    location: JPD.txt
  datasource:
    url: jdbc:postgresql://pctaller.ct0242yuovwd.eu-west-3.rds.amazonaws.com:5432/pctaller
    username: josepe
    password: Fhl7OEGCfKGvYN55mcPo
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      generate-ddl: true
      hibernate:
        "[format_sql]": true
        "[show_sql]": true
        "[default_schema]": pctaller
server:
  port: 5555 
logging:
  level:
   "[org.springframework.web]": TRACE
